name: Build and Test

# Déclenche sur push et pull request
on:
  push:
    branches:
      - main
      - '**/feature/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Récupérer le code
      - uses: actions/checkout@v3

      # 2️⃣ Installer .NET 8
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      # 3️⃣ Restaurer les dépendances
      - name: Restore dependencies
        run: dotnet restore

      # 4️⃣ Compiler le projet
      - name: Build
        run: dotnet build --no-restore --configuration Release

      # 5️⃣ Lancer les tests unitaires (si présents)
      - name: Run Tests
        run: dotnet test --no-build --verbosity normal
